package org.client;

public enum MenuStatus {
    START_MENU,
    SELECT_LEVEL_MENU,
    PLAY_GAME_MENU,
    SETTINGS_MENU,
    RULES_MENU,
    ABOUT_AUTHORS_MENU,
    PAUSE_GAME_MENU,
    DEFEAT_GAME_MENU,
    WIN_GAME_MENU,
    SELECT_PLAYER_MENU
}
